/**
 * Builder for Dane Rudhyar: The Astrological Houses
 * Subtitle: The Spectrum of Individual Experience
 * Standard: BKRS v2.0 Production Master
 * Architecture: 10 Comprehensive Units | The Humanistic Philosophy of the 12 Fields of Consciousness
 */

const fs = require('fs');
const path = require('path');

const targetDir = path.join(__dirname, '..', '..', 'docs', 'distillations', 'astrological-houses-rudhyar');
if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

const units = [
  {
    unit_id: "unit-01",
    unit_number: 1,
    chapter_number: 1,
    title: "Part I: Why Houses? — The Dial of Experience & Space vs. Time Epistemology",
    scope: "Chapter 1: The philosophy of houses, Earth-centered orientation, Space (Houses) vs. Time (Signs), and the individual as an active experiencer",
    epistemic_status: "HUMANISTIC_ONTOLOGY & PHENOMENOLOGICAL_ORIENTATION",
    materiality: "CRITICAL",
    core_theme: "The radical humanistic reorientation of astrology: houses represent individual space and fields of experience, whereas signs represent collective species conditioning and cyclic time.",
    textual_analysis: [
      "Dane Rudhyar shatters the fatalistic, fortune-telling paradigm of medieval astrology by establishing a rigorous philosophical distinction between Signs and Houses. The Zodiac of signs is determined by the Earth's annual revolution around the Sun; it is an orbital cycle representing the flow of generic life energy, collective human nature, biological seasons, and species-conditioning. Signs answer the question: 'What kind of cosmic energy is operating?'",
      "Houses, by contrast, are determined by the Earth's daily axial rotation on its own center; they represent the individual human being standing erect on the Earth's surface at a specific geographical coordinate looking out at the sky. Houses represent Space, individual orientation, conscious awareness, and specific fields of personal experience. Houses answer the question: 'Where in my life, and for what individual purpose, must this energy be consciously experienced?'",
      "The Dial of Experience: A birth chart is not a static sentence of doom; it is an unfolding clock of experiential opportunities. The 12 houses constitute a continuous, unbroken spectrum of 12 developmental phases through which an individual consciousness awakens, confronts society, assimilates culture, and transforms into a mature, self-actualized 'Person-in-Community.'",
      "Individual vs. Collective: When an astrologer interprets planets only through signs, they treat the person as a helpless biological specimen driven by collective instincts. When planets are interpreted through houses, the person is addressed as a sovereign spiritual agent capable of giving conscious meaning and creative purpose to life challenges."
    ],
    verbatim_quote: "The signs of the zodiac are fields of life energy; the astrological houses are fields of human experience. The zodiac is the cosmic rhythm of the collective; the houses are the existential dial of the individual soul.",
    operational_heuristic: "Never interpret a planet's sign without anchoring it in its house: the sign defines the functional temperament and generic psychological drive, but the house defines the concrete existential arena where the native must achieve self-mastery.",
    key_motifs: [
      "Space (Houses) vs. Time (Signs)",
      "Daily Axial Rotation vs. Annual Revolution",
      "The Dial of Individual Experience",
      "Person-Centered Astrology",
      "Biological Conditioning vs. Individual Purpose"
    ]
  },
  {
    unit_id: "unit-02",
    unit_number: 2,
    chapter_number: 2,
    title: "Part I: The Cross of Awareness & The Four Quadrants of Consciousness",
    scope: "Chapter 2: The Two Axes (Horizon & Meridian), The Cross of Awareness (Asc/Desc, MC/IC), and the 4 Quadrants",
    epistemic_status: "CROSS_OF_AWARENESS & QUADRANT_PSYCHODYNAMICS",
    materiality: "CRITICAL",
    core_theme: "The structural foundation of the houses: the intersection of the Horizon (Awareness of Self/Other) and Meridian (Power of Integration/Action), forming the four quadrants of human consciousness.",
    textual_analysis: [
      "Rudhyar reveals that the 12 houses are generated by the intersection of two fundamental astronomical axes: the Horizon (East-West) and the Meridian (South-North). These axes form the 'Cross of Awareness' upon which individual consciousness is crucified and resurrected.",
      "The Horizontal Axis (Ascendant — Descendant): The axis of Awareness and Relationship. The Ascendant (East) represents the sunrise of consciousness, the dawn of the unique 'I Am', the discovery of subjective individual identity. The Descendant (West) represents the sunset, where the solitary ego encounters the 'Thou'—the discovery of the Other, partnership, and social contract.",
      "The Vertical Axis (Nadir/IC — Midheaven/MC): The axis of Power and Integration. The Nadir or Imum Coeli (IC / North) represents the dark, subterranean roots of being, personal integration, ancestry, psychological foundation, and domestic sanctuary. The Midheaven (MC / South) represents the noon culmination, public standing, professional achievement, social participation, and collective authority.",
      "The Four Quadrants of Psychological Unfolding: 1) First Quadrant (Houses 1, 2, 3): Beneath the horizon, East. The subjective awakening of the individual self, discovery of bodily resources, and exploratory mental naming; 2) Second Quadrant (Houses 4, 5, 6): Beneath the horizon, West. Personal emotional integration, creative self-expression, and the crisis of self-adjustment through labor; 3) Third Quadrant (Houses 7, 8, 9): Above the horizon, West. Objective encounter with others, shared socio-cultural contracts, and expansive philosophical worldviews; 4) Fourth Quadrant (Houses 10, 11, 12): Above the horizon, East. Public participation, collective cultural reform, and the spiritual closure/transmutation of the entire cycle."
    ],
    verbatim_quote: "The Horizon is the line of consciousness: at the Ascendant I discover myself; at the Descendant I discover the partner. The Meridian is the line of power: at the Nadir I strike deep roots into reality; at the Zenith I flower into collective society.",
    operational_heuristic: "Assess chart hemispheric balance: an emphasis below the horizon indicates a subjective, introspective quest for personal foundation; an emphasis above the horizon demands public, objective, and sociological engagement.",
    key_motifs: [
      "The Cross of Awareness",
      "Horizon (Awareness) vs. Meridian (Power)",
      "Ascendant (I Am) vs. Descendant (Thou)",
      "Nadir/IC (Roots) vs. Zenith/MC (Social Flower)",
      "The 4 Quadrants of Unfolding"
    ]
  },
  {
    unit_id: "unit-03",
    unit_number: 3,
    chapter_number: 3,
    title: "Part I: The Threefold Rhythm of Experience — Action, Reaction & Integration",
    scope: "Chapter 3: The dialectical rhythm within each quadrant: Angular (Action/Initiative), Succedent (Reaction/Resources), Cadent (Integration/Learning/Crisis)",
    epistemic_status: "DIALECTICAL_TRIPOD & EXPERIENTIAL_RESONANCE",
    materiality: "CRITICAL",
    core_theme: "The universal 3-phase dialectic operating within every quadrant: Angular houses generate Action/Thesis; Succedent houses force Reaction/Antithesis; Cadent houses produce Integration/Synthesis.",
    textual_analysis: [
      "Rudhyar demonstrates that human experience does not move in a haphazard line, but follows a universal threefold dialectical pulse: Thesis (Action), Antithesis (Reaction/Resources), and Synthesis (Transformation/Understanding). Each of the four quadrants contains one Angular, one Succedent, and one Cadent house.",
      "Phase 1: The Angular Houses (1, 4, 7, 10) — The Realm of Action: Here the individual takes direct initiative. In House 1, action as self-discovery; in House 4, action as establishing a home; in House 7, action as forming relationship; in House 10, action as public ambition and collective leadership. These are the dynamic engines of biography.",
      "Phase 2: The Succedent Houses (2, 5, 8, 11) — The Realm of Reaction, Value & Resources: Action inevitably produces consequences and requires sustenance. In House 2, what physical resources substantiate the self? In House 5, what creative progeny or emotional enjoyment reacts from the home? In House 8, what shared assets and legal contracts react from marriage? In House 11, what social ideals and friendships react from professional status?",
      "Phase 3: The Cadent Houses (3, 6, 9, 12) — The Realm of Integration, Learning & Crisis: Resources and reactions must be mentally processed, integrated, or transmuted. In House 3, learning to communicate and synthesize environment; in House 6, the crisis of self-adjustment, retraining, and health maintenance; in House 9, the philosophical synthesis of law and abstract religion; in House 12, the spiritual liquidation of past karmic debts and seed-preparation for rebirth."
    ],
    verbatim_quote: "Life is a continuous rhythm of three beats: to act, to suffer the reaction of the act, and to understand the meaning of the action. Without the cadent house, experience remains unassimilated and blindly repeats itself.",
    operational_heuristic: "Identify where a client experiences stagnation: if blocked in an angular house, they fear taking initiative; if blocked in a succedent house, they cannot manage resources; if blocked in a cadent house, they fail to assimilate life lessons.",
    key_motifs: [
      "Threefold Dialectic (Thesis, Antithesis, Synthesis)",
      "Angular (Action / Initiative)",
      "Succedent (Reaction / Substantiation)",
      "Cadent (Integration / Learning / Crisis)",
      "The Cyclic Evolution of Consciousness"
    ]
  },
  {
    unit_id: "unit-04",
    unit_number: 4,
    chapter_number: 4,
    title: "Part II: The First Quadrant — The Emerging Individual (Houses 1, 2, 3)",
    scope: "Chapters 4, 5, 6: First House (Awareness of Self), Second House (Substantiation/Resources), Third House (Environment & Mind)",
    epistemic_status: "INDIVIDUAL_EMERGENCE & SUBJECTIVE_DIALECTIC",
    materiality: "CRITICAL",
    core_theme: "The birth of subjective identity: the First House awakens personal consciousness; the Second House substantiates it with physical possessions and vitality; the Third House explores the immediate environment.",
    textual_analysis: [
      "The First House: Awareness of Self. The 1st house is the supreme existential portal. It does not simply represent physical looks; it represents the pure, undifferentiated experience of being 'This unique Person'. The sign on the Ascendant describes the intuitive lens through which the native must look if they are to fulfill their dharma. It is the archetype seeking embodiment.",
      "The Second House: Substantiation & Possession. The newborn self must have a body and tools to survive. The 2nd house represents what the individual claims as 'Mine': physical energy, inherited biological traits, money, possessions, and personal values. Rudhyar cautions against the materialistic reduction of the 2nd house: wealth is merely crystallized energy meant to substantiate individual purpose.",
      "The Third House: Environmental Exploration & Practical Mind. The emerging self must map its immediate terrain. The 3rd house rules sensory perception, basic mental classification, verbal speech, relationships with brothers and sisters, and short exploratory excursions. It represents the everyday intellect organizing raw sensory data into workable concepts."
    ],
    verbatim_quote: "The First House is who I am; the Second House is what I have to work with; the Third House is how I explore and name my immediate world.",
    operational_heuristic: "In examining the 1st Quadrant, evaluate the developmental chain: if a native has a brilliant 1st house vision but an afflicted 2nd house, their ideas fail to materialize for lack of grounded physical resources.",
    key_motifs: [
      "First House (Pure Awareness of Self)",
      "Second House (Substantiation & Resources)",
      "Third House (Environmental Exploration)",
      "The Ascendant as Dharma Lens",
      "Possession as Crystallized Energy"
    ]
  },
  {
    unit_id: "unit-05",
    unit_number: 5,
    chapter_number: 5,
    title: "Part II: The Second Quadrant — Personal Integration & Crisis of Adjustment (Houses 4, 5, 6)",
    scope: "Chapters 7, 8, 9: Fourth House (Rooting & Home), Fifth House (Creative Projection), Sixth House (Self-Adjustment & Service)",
    epistemic_status: "PERSONAL_INTEGRATION & FUNCTIONAL_CRISIS",
    materiality: "CRITICAL",
    core_theme: "Securing inner emotional stability: the Fourth House establishes roots and inner security; the Fifth House projects creative individuality; the Sixth House enforces self-adjustment, discipline, and health.",
    textual_analysis: [
      "The Fourth House: Rooting & Emotional Integration. The Nadir (IC) is the deepest point of the chart. The 4th house represents the psychological foundation, the home, the womb, parental conditioning, and the capacity to feel centered in oneself. Without a stable 4th house root system, an individual cannot withstand the storms of public life in the 10th house.",
      "The Fifth House: Creative Self-Expression & Emotional Release. Rooted in the 4th house, the individual now seeks to leave a personal mark on the world. The 5th house rules creative arts, play, romance, speculation, and children. Rudhyar stresses that the 5th house is the projection of the ego: whether one paints a masterpiece, sires a child, or engages in passionate love, one is externalizing one's subjective self.",
      "The Sixth House: Self-Adjustment, Service & Health. The 6th house is the crucial hinge between the individual hemisphere and the social hemisphere. Before one can encounter equals in the 7th house, one must undergo personal purification and retraining. The 6th house rules work, technical apprenticeships, daily discipline, and bodily health. Disease (dis-ease) is interpreted humanistically as an indicator that the ego is out of harmony with its life purpose, demanding corrective self-adjustment."
    ],
    verbatim_quote: "The Sixth House is the crucible of personal transformation: here the ego must learn patience, service, and skill. Illness in the sixth house is not a curse, but the body's plea for conscious realignment.",
    operational_heuristic: "Treat 6th house crises as diagnostic pointers: chronic health issues or employment conflicts signal that the native's subjective desires (5th house) are colliding with objective realities, demanding retraining and ego humility.",
    key_motifs: [
      "Fourth House (Rooting & Emotional Center)",
      "Fifth House (Creative Ego Projection)",
      "Sixth House (Self-Adjustment & Discipline)",
      "Disease as Functional Disalignment",
      "The Crucible of Apprenticeship"
    ]
  },
  {
    unit_id: "unit-06",
    unit_number: 6,
    chapter_number: 6,
    title: "Part II: The Third Quadrant — The Realm of Relationship & Social Contract (Houses 7, 8, 9)",
    scope: "Chapters 10, 11, 12: Seventh House (Awareness of the Other), Eighth House (Regeneration & Shared Power), Ninth House (Philosophical Expansion)",
    epistemic_status: "INTERPERSONAL_RELATIONALITY & SOCIO_CULTURAL_EXPANSION",
    materiality: "CRITICAL",
    core_theme: "The awakening of relational and social consciousness: the Seventh House meets the Other; the Eighth House merges resources and faces transformation; the Ninth House synthesizes meaning through philosophy and law.",
    textual_analysis: [
      "The Seventh House: Awareness of the Other & Partnership. Rising above the western horizon, the native crosses from solitary selfhood into interpersonal co-existence. The 7th house rules marriage, business partners, open contracts, and equals. Rudhyar stresses that the partner chosen in the 7th house is an exteriorized projection of the native's own unintegrated psychological qualities (the Jungian Anima/Animus or Shadow).",
      "The Eighth House: Regeneration, Shared Power & Ultimate Surrender. When two individuals unite in the 7th house, they must pool their resources and negotiate shared values. The 8th house rules joint finances, inheritances, corporate assets, sexuality as an ego-merging experience, and psychological death/rebirth. It is the house of regenerative crisis: the individual must die to selfish autonomy in order to participate in a larger collective organism.",
      "The Ninth House: Expansion of Understanding & Abstract Philosophy. Following the intense emotional trials of the 8th house, the mind seeks universal principles. The 9th house rules higher education, legal systems, comparative religion, abstract philosophy, and journeys to foreign lands. It expands the provincial consciousness into cosmic understanding."
    ],
    verbatim_quote: "In the Seventh House I see the face of the partner; in the Eighth House we pool our blood, our money, and our souls; in the Ninth House we build the cathedral of philosophy to understand what our union means.",
    operational_heuristic: "When evaluating marital or business conflict, analyze the 7th-to-8th house progression: a partnership begins with harmonious 7th-house vows, but will collapse in the 8th house if partners cannot surrender financial and psychological dominance.",
    key_motifs: [
      "Seventh House (Encounter with the Other)",
      "Eighth House (Regeneration & Mutual Surrender)",
      "Ninth House (Philosophical Expansion)",
      "Partnership as Shadow Mirror",
      "Dying to the Ego for Collective Union"
    ]
  },
  {
    unit_id: "unit-07",
    unit_number: 7,
    chapter_number: 7,
    title: "Part II: The Fourth Quadrant — Collective Participation & Spiritual Culmination (Houses 10, 11, 12)",
    scope: "Chapters 13, 14, 15: Tenth House (Social Integration & Profession), Eleventh House (Social Reform & Ideals), Twelfth House (Transmutation & Seed Rebirth)",
    epistemic_status: "COLLECTIVE_ACTUALIZATION & TRANSMUTATIVE_CLOSURE",
    materiality: "CRITICAL",
    core_theme: "Culminating the cycle of experience: the Tenth House achieves public standing; the Eleventh House reforms culture through visionary friendships; the Twelfth House dissolves past karma into the spiritual seed of new life.",
    textual_analysis: [
      "The Tenth House: Social Integration & Collective Destiny. The Midheaven (MC) is the noon peak of worldly visibility. The 10th house represents the native's profession, public reputation, social responsibility, and collective authority. Rudhyar redefines career: it is not merely earning a paycheck, but fulfilling an indispensable function within the organic body of society.",
      "The Eleventh House: Creative Social Participation, Ideals & Reform. Reacting against the rigid institutional structures of the 10th house, the 11th house seeks cultural renewal. It rules friends, professional associations, progressive ideals, humanitarian movements, and revolutionary visions. Here individuals gather not because of family ties (4th house) or legal contracts (7th house), but because of shared dedication to a better future.",
      "The Twelfth House: Transmutation, Closure & The Seed for Rebirth. The final house is the most mysterious and misunderstood. Traditional astrology termed it the house of 'self-undoing' and imprisonment. Rudhyar reclaims it as the house of Transmutation and Culmination. It represents the unconscious accumulation of past cycles (karma), institutional isolation, monastic retreat, and psychological liquidation. It is the autumn when the leaves fall, the fruit rots, and only the pure indestructible seed remains to await rebirth in the 1st house."
    ],
    verbatim_quote: "The Twelfth House is the harvest of the whole life cycle: whatever was unfinished becomes a shadow of guilt and confinement; whatever was understood becomes the golden seed of spiritual illumination.",
    operational_heuristic: "Differentiate between 12th house agony and 12th house enlightenment: encourage clients with strong 12th house placements to embrace solitude, creative meditation, and charitable service, converting karmic burdens into spiritual seeds.",
    key_motifs: [
      "Tenth House (Collective Function & Public Destiny)",
      "Eleventh House (Cultural Reform & Visionary Fellowship)",
      "Twelfth House (Transmutation & The Indestructible Seed)",
      "The Liquidation of Past Karma",
      "Autumn of Consciousness & Spring of Rebirth"
    ]
  },
  {
    unit_id: "unit-08",
    unit_number: 8,
    chapter_number: 8,
    title: "Part III: The Polarities of the Houses — Dynamic Complementarity Across the Six Axes",
    scope: "Part III: The 6 House Axes: 1-7 (Identity/Relationship), 2-8 (Possession/Shared Power), 3-9 (Environment/Philosophy), 4-10 (Roots/Public Destiny), 5-11 (Individual/Collective Creation), 6-12 (Service/Transmutation)",
    epistemic_status: "POLAR_COMPLEMENTARITY & AXIAL_INTEGRATION",
    materiality: "CRITICAL",
    core_theme: "The profound structural principle that houses operate in diametrical pairs: each house cannot be understood in isolation, but only through its dynamic polarity with the opposite house.",
    textual_analysis: [
      "Rudhyar insists that no house exists as an isolated compartment; every house is half of an energetic axis. The six house axes represent the six fundamental polarities of human existence, and psychological neurosis occurs when an individual clings to one pole while repressing the other.",
      "Axis 1 — 7 (Awareness of Self vs. Awareness of Other): The axis of Individual Existence. An overdeveloped 1st house creates solipsistic narcissism; an overdeveloped 7th house creates codependent helplessness. Healthy integration means knowing who one is while relating fully to the partner.",
      "Axis 2 — 8 (Personal Resources vs. Shared Transformation): The axis of Substance and Power. Clinging to the 2nd house creates miserly hoarding; drowning in the 8th house creates financial exploitation. Integration requires using personal wealth to serve mutual, regenerative partnerships.",
      "Axis 3 — 9 (Concrete Mind vs. Abstract Philosophy): The axis of Thought and Meaning. The 3rd house collects local facts; the 9th house weaves facts into universal laws. Facts without philosophy are trivial gossip; philosophy without facts is disconnected dogma.",
      "Axis 4 — 10 (Inner Home vs. Public Standing): The axis of Stability and Destiny. Neglecting the 4th house for career creates a hollow, burn-out existence; hiding in the 4th house cripples social contribution.",
      "Axis 5 — 11 (Personal Creative Pride vs. Collective Vision): The axis of Creative Expression. The 5th house creates for personal joy; the 11th house creates for social transformation.",
      "Axis 6 — 12 (Daily Technical Labor vs. Cosmic Transmutation): The axis of Purification and Surrender. The 6th house fixes immediate mechanical and biological breakdowns; the 12th house surrenders to universal spiritual currents."
    ],
    verbatim_quote: "Opposite houses are not enemies; they are the two poles of a single electric current. To master the first house, you must honor the seventh; to achieve the tenth, you must be grounded in the fourth.",
    operational_heuristic: "Whenever a client experiences severe pathology in a specific house, inspect the opposite house: the therapeutic cure always lies in activating the neglected complementary pole of that axis.",
    key_motifs: [
      "Six Polar Axes of Experience",
      "Dynamic Complementarity",
      "1-7 (Self/Other Polarity)",
      "4-10 (Home/Public Destiny Polarity)",
      "Therapeutic Axial Rebalancing"
    ]
  },
  {
    unit_id: "unit-09",
    unit_number: 9,
    chapter_number: 9,
    title: "Part III: Planetary Distribution Across the Houses — Hemispheric & Pattern Delineation",
    scope: "Part III: Planetary concentrations, empty houses, intercepted signs, and hemispheric distribution patterns",
    epistemic_status: "STRUCTURAL_GESTALT & HEMISPHERIC_CONCENTRATION",
    materiality: "IMPORTANT",
    core_theme: "Reading the holistic pattern of the chart: what hemispheric weight reveals about psychological destiny, and how to interpret empty houses and intercepted signs humanistically.",
    textual_analysis: [
      "Rudhyar provides a masterclass in structural chart synthesis, moving beyond isolated planetary placements to examine the holistic geometry of the horoscope.",
      "Hemispheric Dynamics: 1) Eastern Hemisphere (Houses 10, 11, 12, 1, 2, 3): Planets clustered around the Ascendant indicate a self-motivated, proactive destiny where the individual creates their own opportunities and shapes their environment; 2) Western Hemisphere (Houses 4, 5, 6, 7, 8, 9): Planets clustered around the Descendant indicate a fate-dependent, responsive destiny where life unfolds through encounters with others and social demands; 3) Northern Hemisphere (Houses 1 through 6): An introverted, deeply subjective focus on personal integration; 4) Southern Hemisphere (Houses 7 through 12): An extroverted, public focus on social achievement.",
      "Demystifying Empty Houses: Beginners often panic when they see empty houses, assuming that area of life is nonexistent or doomed. Rudhyar demonstrates that an empty house simply means that field of experience is not a primary arena of karmic struggle or compulsive focus; it functions smoothly according to the condition of the house's ruling planet.",
      "Intercepted Signs: When a zodiacal sign is entirely enclosed within a house without touching a cusp, its qualities are internalized, latent, and require deep maturity to unlock."
    ],
    verbatim_quote: "An empty house is not an empty life; it is an open room where the soul can walk freely without the burden of heavy furniture.",
    operational_heuristic: "Never declare an empty house inactive: trace its planetary ruler and aspect network to discover how that domain of experience is seamlessly supported by other active centers of consciousness.",
    key_motifs: [
      "Eastern vs. Western Hemispheric Destiny",
      "Northern vs. Southern Focus",
      "The Myth of Empty Houses",
      "Intercepted Signs as Latent Potentials",
      "Holistic Chart Gestalt"
    ]
  },
  {
    unit_id: "unit-10",
    unit_number: 10,
    chapter_number: 10,
    title: "Humanistic Synthesis: The Astrologer as an Agent of Transformation & Self-Actualization",
    scope: "Conclusion: Ethical mandate of the person-centered astrologer, non-deterministic counseling, and guiding the client toward individuation",
    epistemic_status: "HUMANISTIC_ETHICS & COUNSELING_PRAXIS",
    materiality: "CRITICAL",
    core_theme: "The ethical and therapeutic role of the modern astrologer: freeing clients from fatalistic terror and guiding them to consciously fulfill their unique existential potential.",
    textual_analysis: [
      "In the concluding synthesis of *The Astrological Houses*, Dane Rudhyar outlines the noble ethical mandate of the person-centered, humanistic astrologer. He condemns traditional fatalistic predictive practices that induce crippling anxiety in vulnerable clients by forecasting accidents, illness, or divorce as unavoidable doom.",
      "Astrology as Psychological Hygiene: The purpose of a birth chart reading is not to satisfy morbid curiosity about the future, but to bring order, meaning, and cosmic perspective to the client's present challenges. The chart reveals the archetypal blueprint of who the client was born to become.",
      "The Event vs. The Experiencer: Rudhyar formulates his supreme philosophical axiom: 'Events do not happen to people; people happen to events.' Two individuals can experience the exact same external transit (e.g., Pluto crossing the Midheaven); an unconscious person experiences it as catastrophic ruin and scandal, while a conscious person uses it to purge corruption, eliminate superficial ambitions, and rise into profound moral integrity.",
      "Guiding the Client through the 12 Houses: The master counselor uses the 12 houses as a therapeutic map, helping the client recognize which quadrant of life is currently asking for courage, which for adjustment, and which for spiritual surrender."
    ],
    verbatim_quote: "Events do not happen to people; people happen to events. What is important is not the external event, but the quality of consciousness with which you meet the event and transform it into wisdom.",
    operational_heuristic: "In every astrological consultation, reframe fatalistic external predictions into conscious psychological invitations: ask not 'What will happen to me?', but 'What quality of consciousness must I cultivate to master this moment?'",
    key_motifs: [
      "Events Do Not Happen to People",
      "Person-Centered Astrological Counseling",
      "Therapeutic De-conditioning",
      "Reframing Doom into Evolutionary Dharma",
      "The Astrologer as Priest of Consciousness"
    ]
  }
];

function generateMarkdown(units) {
  let md = `# Dane Rudhyar: The Astrological Houses
## The Spectrum of Individual Experience · BKRS v2.0 Deep Forensic Master Codex

---

### Archival Metadata
- **Author:** Dane Rudhyar (1895–1985)
- **Publication Date:** 1972 (Doubleday & Company, Inc. / CRCS Publications)
- **Philosophical Tradition:** Humanistic Astrology, Transpersonal Psychology, Carl Jung Depth Synthesis, Holism
- **Curriculum Role:** The Humanistic & Cyclical Foundation of Astrological Houses (Book 7 of the Master Curriculum)

---

## Executive Summary: The Revolution of Person-Centered Astrology

First published in 1972, Dane Rudhyar's *The Astrological Houses: The Spectrum of Individual Experience* fundamentally revolutionized modern astrology. For centuries, traditional European and medieval practitioners treated the twelve houses as static, fatalistic buckets of external fortune—predicting inheritances, enemies, imprisonments, and sudden deaths with deterministic finality.

Rudhyar, drawing upon the depth psychology of Carl G. Jung, modern holism, and Eastern philosophy, completely discarded this fatalistic apparatus. He established that **houses represent the dial of individual human experience**. While the zodiac of signs represents the Earth's orbit and generic biological/collective life energy (Space vs. Time), the twelve houses represent the Earth's daily axial rotation—the perspective of a unique individual consciousness standing at a specific geographical location on the Earth's surface.

### The Core Architectural Pillars:
1. **The Cross of Awareness:** The horizontal axis (Horizon: Ascendant/Descendant) establishes the line of **Consciousness and Relationship** (Awareness of Self vs. Awareness of the Other). The vertical axis (Meridian: Nadir/Midheaven) establishes the line of **Power and Integration** (Rooting in the Personal Unconscious vs. Public Flower in Collective Destiny).
2. **The Four Quadrants:** The psychological progression from Subjective Awakening (Quadrant 1) to Personal Integration (Quadrant 2), Objective Relationship (Quadrant 3), and Collective Actualization (Quadrant 4).
3. **The Threefold Rhythm:** In every quadrant, life moves through a 3-beat dialectic: **Action / Thesis** (Angular houses), **Reaction / Resources / Antithesis** (Succedent houses), and **Integration / Learning / Synthesis** (Cadent houses).
4. **The Six Polar Axes:** Houses must never be read in isolation; they are dynamic dipole currents (1-7, 2-8, 3-9, 4-10, 5-11, 6-12).

---

## Detailed Structural Analysis of the Ten Units

`;

  units.forEach(u => {
    md += `### ${u.title}\n\n`;
    md += `- **Unit ID:** \`${u.unit_id}\`\n`;
    md += `- **Epistemic Classification:** \`${u.epistemic_status}\`\n`;
    md += `- **Materiality Level:** \`${u.materiality}\`\n`;
    md += `- **Core Theme:** ${u.core_theme}\n\n`;
    md += `#### Forensic Textual Analysis\n\n`;
    u.textual_analysis.forEach(p => {
      md += `${p}\n\n`;
    });
    md += `> **Rudhyar Humanistic Verbatim:**\n`;
    md += `> "${u.verbatim_quote}"\n\n`;
    md += `**Operational Heuristic for Practitioners:**\n`;
    md += `*${u.operational_heuristic}*\n\n`;
    md += `**Key Motifs & Terminology:** ${u.key_motifs.map(m => `\`${m}\``).join(' · ')}\n\n`;
    md += `---\n\n`;
  });

  md += `## The Complete Twelve-House Field Guide

| House | Quadrant | Rhythm | Axis | Core Archetypal Meaning | Psychological Challenge |
| :--- | :--- | :--- | :--- | :--- | :--- |
| **1st House** | 1st (Subjective) | Angular (Action) | Self / Other (1-7) | Awareness of Self, Pure Being, Individual Identity | Escaping narcissism; discovering true dharma |
| **2nd House** | 1st (Subjective) | Succedent (Resources) | Substance / Power (2-8) | Substantiation, Inherited Vitality, Personal Wealth | Avoiding possessive hoarding; managing energy |
| **3rd House** | 1st (Subjective) | Cadent (Integration) | Mind / Meaning (3-9) | Environmental Exploration, Everyday Mind, Sibling Ties | Moving beyond mere superficial mental chatter |
| **4th House** | 2nd (Integration) | Angular (Action) | Roots / Destiny (4-10) | Rooting, Emotional Center, Home, Deep Foundations | Breaking free from toxic parental unconscious patterns |
| **5th House** | 2nd (Integration) | Succedent (Resources) | Creative Expression (5-11) | Creative Self-Expression, Play, Romance, Progeny | Overcoming ego vanity; creating with authentic soul |
| **6th House** | 2nd (Integration) | Cadent (Integration) | Service / Surrender (6-12) | Self-Adjustment, Discipline, Service, Bodily Health | Healing dis-ease; mastering craftsmanship with humility |
| **7th House** | 3rd (Relational) | Angular (Action) | Self / Other (1-7) | Awareness of the Other, True Partnership, Equality | Recognizing the partner as the unintegrated shadow |
| **8th House** | 3rd (Relational) | Succedent (Resources) | Substance / Power (2-8) | Regenerative Surrender, Joint Resources, Death/Rebirth | Surrendering the isolated ego to collective merger |
| **9th House** | 3rd (Relational) | Cadent (Integration) | Mind / Meaning (3-9) | Philosophical Expansion, Higher Law, Cosmic Meaning | Synthesizing diverse dogmas into lived wisdom |
| **10th House** | 4th (Collective) | Angular (Action) | Roots / Destiny (4-10) | Public Standing, Profession, Social Responsibility | Resisting authoritarian hubris; serving community |
| **11th House** | 4th (Collective) | Succedent (Resources) | Creative Expression (5-11) | Visionary Fellowship, Social Reform, Progressive Ideals | Cultivating friendships based on future ideals |
| **12th House** | 4th (Collective) | Cadent (Integration) | Service / Surrender (6-12) | Transmutation, Karma Liquidation, Seed of Rebirth | Releasing guilt; transforming crisis into illumination |

---

## Rudhyar's Golden Rules for Interpreting the Horoscope

1. **Rule of the Native's Primacy:** The chart does not dictate what you *must* do; it reveals the optimal path of how you can become fully yourself.
2. **Rule of Hemispheric Balance:** Look at the four quadrants before inspecting single planets. Heavy East = self-determined pioneer; heavy West = relationship-centered collaborator; heavy North = introspective foundation-builder; heavy South = public cultural actor.
3. **Rule of the Axis:** Never interpret any house affliction without diagnosing its opposite number. Healing a 6th-house chronic ailment always requires activating 12th-house spiritual surrender and psychological release.
4. **Rule of Transmutation:** Every 'negative' placement is simply an unassimilated creative potential waiting for conscious integration.
`;

  return md;
}

function generateReaderHtml(units) {
  const cardsHtml = units.map(u => `
    <article class="unit-card" id="${u.unit_id}">
      <div class="unit-header">
        <span class="unit-badge">${u.epistemic_status}</span>
        <span class="unit-materiality ${u.materiality.toLowerCase()}">${u.materiality}</span>
      </div>
      <h2 class="unit-title">${u.title}</h2>
      <div class="unit-scope">${u.scope}</div>
      <div class="unit-core-insight">${u.core_theme}</div>
      <div class="unit-prose">
        ${u.textual_analysis.map(p => `<p>${p}</p>`).join('')}
      </div>
      <blockquote class="verbatim-quote">
        "${u.verbatim_quote}"
        <cite>— Dane Rudhyar, The Astrological Houses</cite>
      </blockquote>
      <div class="heuristic-box">
        <div class="heuristic-header">HUMANISTIC ASTROLOGICAL HEURISTIC</div>
        <div class="heuristic-body">${u.operational_heuristic}</div>
      </div>
      <div class="motifs-bar">
        <strong>Key Astrological Motifs:</strong>
        ${u.key_motifs.map(m => `<span class="motif-tag">${m}</span>`).join(' ')}
      </div>
      <script type="application/json" id="trace-data-${u.unit_id}">
        ${JSON.stringify({
          unit_id: u.unit_id,
          title: u.title,
          epistemic_status: u.epistemic_status,
          materiality: u.materiality,
          motifs: u.key_motifs
        })}
      </script>
    </article>
  `).join('\n');

  return `<!DOCTYPE html>
<html lang="en" data-theme="cream">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>The Astrological Houses — Dane Rudhyar | BKRS Master Reader</title>
  <link rel="stylesheet" href="../../assets/css/reader-shell.css">
  <style>
    :root {
      --bg-canvas: #fbf9f4;
      --bg-card: #ffffff;
      --bg-subtle: #f4efe4;
      --text-main: #1c1917;
      --text-muted: #57534e;
      --accent-crimson: #85221c;
      --border-light: #e7dfd3;
      --border-dark: #7a7060;
      --shadow-sm: 0 2px 8px rgba(28, 25, 23, 0.04);
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      background-color: var(--bg-canvas);
      color: var(--text-main);
      font-family: Georgia, 'EB Garamond', serif;
      font-size: 16px;
      line-height: 1.65;
      padding: 24px;
    }
    .reader-container {
      max-width: 900px;
      margin: 0 auto;
    }
    .doc-header {
      border-bottom: 2px solid var(--text-main);
      padding-bottom: 16px;
      margin-bottom: 28px;
    }
    .doc-kicker {
      font-family: -apple-system, sans-serif;
      font-size: 11px;
      font-weight: 700;
      letter-spacing: 0.15em;
      text-transform: uppercase;
      color: var(--accent-crimson);
      margin-bottom: 6px;
    }
    .doc-title {
      font-size: 26px;
      font-weight: 700;
      line-height: 1.25;
      margin-bottom: 6px;
    }
    .doc-author {
      font-size: 15px;
      font-style: italic;
      color: var(--text-muted);
      margin-bottom: 12px;
    }
    .view-tabs {
      display: flex;
      gap: 10px;
      margin-bottom: 24px;
      border-bottom: 1px solid var(--border-light);
      padding-bottom: 8px;
    }
    .view-tab {
      font-family: -apple-system, sans-serif;
      font-size: 13px;
      font-weight: 600;
      padding: 6px 14px;
      border: 1px solid var(--border-dark);
      background: var(--bg-card);
      border-radius: 4px;
      cursor: pointer;
      text-decoration: none;
      color: var(--text-main);
    }
    .view-tab.active {
      background: var(--text-main);
      color: #fff;
    }
    .unit-card {
      background: var(--bg-card);
      border: 1px solid var(--border-light);
      border-radius: 4px;
      padding: 24px;
      margin-bottom: 28px;
      box-shadow: var(--shadow-sm);
    }
    .unit-header {
      display: flex;
      justify-content: space-between;
      margin-bottom: 8px;
      font-family: -apple-system, sans-serif;
      font-size: 11px;
    }
    .unit-badge {
      font-weight: 700;
      color: var(--accent-crimson);
      letter-spacing: 0.06em;
    }
    .unit-materiality {
      font-weight: 700;
      padding: 2px 6px;
      border-radius: 2px;
    }
    .unit-materiality.critical { background: #ffe4e6; color: #9f1239; }
    .unit-materiality.important { background: #fef3c7; color: #92400e; }
    .unit-materiality.textural { background: #e0f2fe; color: #075985; }
    .unit-title {
      font-size: 20px;
      font-weight: 700;
      margin-bottom: 6px;
      line-height: 1.3;
    }
    .unit-scope {
      font-family: -apple-system, sans-serif;
      font-size: 12px;
      color: var(--text-muted);
      margin-bottom: 12px;
    }
    .unit-core-insight {
      font-size: 14px;
      font-style: italic;
      color: #333;
      border-left: 3px solid var(--accent-crimson);
      padding-left: 10px;
      margin-bottom: 16px;
    }
    .unit-prose p {
      margin-bottom: 12px;
      text-align: justify;
    }
    .verbatim-quote {
      border-left: 3px solid var(--text-main);
      padding: 10px 16px;
      font-style: italic;
      background: var(--bg-subtle);
      margin: 16px 0;
      font-size: 14.5px;
    }
    .verbatim-quote cite {
      display: block;
      margin-top: 6px;
      font-size: 12px;
      font-style: normal;
      color: var(--text-muted);
    }
    .heuristic-box {
      border: 1px solid var(--text-main);
      border-left: 4px solid var(--text-main);
      background: #fafafa;
      padding: 12px 14px;
      margin: 16px 0;
    }
    .heuristic-header {
      font-family: -apple-system, sans-serif;
      font-size: 10.5px;
      font-weight: 800;
      color: var(--text-main);
      letter-spacing: 0.08em;
      margin-bottom: 4px;
    }
    .heuristic-body {
      font-size: 13.5px;
      color: #111;
    }
    .motifs-bar {
      font-family: -apple-system, sans-serif;
      font-size: 11.5px;
      color: var(--text-muted);
      margin-top: 14px;
    }
    .motif-tag {
      background: #eee;
      padding: 2px 6px;
      border-radius: 2px;
      color: #222;
      display: inline-block;
      margin: 2px;
    }
  </style>
</head>
<body>
  <div class="reader-container">
    <header class="doc-header">
      <div class="doc-kicker">BKRS Deep Forensic Master Codex · Humanistic Astrological Philosophy</div>
      <h1 class="doc-title">The Astrological Houses: The Spectrum of Individual Experience</h1>
      <div class="doc-author">Dane Rudhyar · Complete Ten-Unit Humanistic Masterwork</div>
      <nav class="view-tabs">
        <a href="#view-journey" class="view-tab active" id="view-journey">View A: Source Journey</a>
        <a href="#view-map" class="view-tab" id="view-map">View B: Relational Map</a>
        <a href="#view-experience" class="view-tab" id="view-experience">View C: Operational Heuristics</a>
      </nav>
    </header>

    <main id="units-wrapper">
      ${cardsHtml}
    </main>
  </div>

  <script src="../../assets/js/reader-controls.js"></script>
</body>
</html>`;
}

// 1. Write knowledge-units.json
fs.writeFileSync(path.join(targetDir, 'knowledge-units.json'), JSON.stringify(units, null, 2), 'utf8');
console.log(`[1/3] Wrote knowledge-units.json (${units.length} units)`);

// 2. Write master-notes.md
const md = generateMarkdown(units);
fs.writeFileSync(path.join(targetDir, 'master-notes.md'), md, 'utf8');
console.log(`[2/3] Wrote master-notes.md (${md.length} characters)`);

// 3. Write index.html
const readerHtml = generateReaderHtml(units);
fs.writeFileSync(path.join(targetDir, 'index.html'), readerHtml, 'utf8');
console.log(`[3/3] Wrote index.html (${readerHtml.length} characters)`);

console.log('\nSUCCESS: Dane Rudhyar: The Astrological Houses successfully built!');
